### ISSUE TITLE
Testing bug on Windows

### ISSUE THREAD

**Issue by nrc** [nrc/rustfmt#306] opened 2015-09-10 21:21 UTC
There seems to be some kind of issue comparing input and output and in tests on Windows. I haven't reproduced myself, so this is kind of vague. See test results: http://pastebin.com/DrnubLU2

I confirmed that running rustfmt on the file works fine, so it is the test which is buggy, not rustfmt itself. Other than that, I don't really know what is going.

cc @rosatamsen

**Comment by SingingTree** [comment] 2015-10-07 10:25
I believe I've just encountered this same bug. Manually running rustfmt works, but the tests fail as in the pastebin. My logs: https://gist.github.com/SingingTree/e31f11bde05a30d5aae0. I've had a cautionary look, but can't find anything immediately wrong. I'm happy to help dig around and reproduce this, and plan on fighting with it myself.

rustc 1.5.0-nightly (32a8567ea 2015-10-05)
binary: rustc
commit-hash: 32a8567ea4ded47ac4cfd39bc808bb8d6f2e119c
commit-date: 2015-10-05
host: x86_64-pc-windows-gnu
release: 1.5.0-nightly

**Comment by SingingTree** [comment] 2015-10-07 12:20
It looks like this issue is being caused by incorrect handling of the path separator on Windows, I've raised the above PR to try and remedy this.

**Comment by cassiersg** [comment] 2015-10-07 13:53
Fixed by #416.

**Closed by cassiersg** 2015-10-07 13:53 UTC
Labels: bug
