### ISSUE TITLE
Bad reformatting in imports.rs

### ISSUE THREAD

**Issue by nrc** [nrc/rustfmt#170] opened 2015-08-03 23:08 UTC
In a call to itemize_list, see https://github.com/cassiersg/rustfmt/commit/e13cc58ac482ddabde98c3919c798ace703190a5#commitcomment-12479359

**Comment by cassiersg** [comment] 2015-08-04 17:37
This was caused by nrc/strings.rs#3 (bug in `cur_offset`), and fixed in rustfmt by cassiersg/rustfmt@5b5927996f9c78e16d75235d5953d072757c8bae.

**Comment by marcusklaas** [comment] 2015-08-14 10:06
This seems to be fixed indeed, closing.

**Closed by marcusklaas** 2015-08-14 10:06 UTC
Labels: bug
