### ISSUE TITLE
option for trailing commas after blocks in match arms

### ISSUE THREAD

**Issue by oli-obk** [nrc/rustfmt#504] opened 2015-10-20 08:35 UTC
match arms that are a block expression don't need commas after them. The style guide isn't clear on this. I add commas after every arm, rustfmt removes them. I'm not sure how to proceed here. Is this a situation of "leave commas that are there, but don't add them" or "fix it to always add" or keep the current "always remove"?

If I get some feedback on this I'll post an RFC to fix the styleguide.

My preference is to always add the comma, since the code becomes more readable. This way you can always distinguish between a closing block and a match arm that is a block. With the gigantic matches that exist in rustc I've felt this to be an issue many times.

**Comment by oli-obk** [comment] 2015-10-20 08:42
An example where rustfmt removes lots of these commas is https://github.com/oli-obk/rust/commit/2eebf526f6b6977b5f8dc6422854af2e54058cc5#diff-8f6f26066e9d5e5392e24be5b11f0a8fL496

**Comment by nrc** [comment] 2015-10-20 22:46
The style we follow in the compiler and which is adopted in rustfmt is to never have unnecessary commas after blocks. We could certainly add an option to add commas after blocks in match arms if you want it, but I don't think we'll change the default.

If you want to make a PR for rustfmt, it would be very simple to do - I'm happy to help out if you'd like.

**Comment by oli-obk** [comment] 2015-10-21 07:09
that sounds reasonable. I'll do that

**Comment by marcusklaas** [comment] 2015-10-23 19:28
Dupe of https://github.com/nrc/rustfmt/issues/173.

**Closed** 2015-10-23 20:22 UTC
Labels: duplicate, easy
