### ISSUE TITLE
rustfmt breaks `for` block that ends with a value-returning `match` stmt

### ISSUE THREAD

**Issue by brianloveswords** [nrc/rustfmt#540] opened 2015-10-26 17:26 UTC
An extremely contrived example:

```rust
use std::collections::BTreeMap;

fn main() {
    let mut map = BTreeMap::new();
    map.insert("key1", "value1");
    map.insert("key2", "value2");
    for (k, v) in map {
        match k {
            "key1" => "this is the first key",
            "key2" => "this is the second key",
            _ => "whatever",
        }; // <-- rustfmt removes this necessary semicolon
    }
}
```

**Comment by marcusklaas** [comment] 2015-10-31 16:09
Dupe of https://github.com/nrc/rustfmt/issues/540.

**Closed by marcusklaas** 2015-10-31 16:09 UTC
Labels: bug
