### ISSUE TITLE
Removing `;` after if or match is not always safe (and breaks code) 

### ISSUE THREAD

**Issue by cristicbz** [nrc/rustfmt#555] opened 2015-10-31 15:58 UTC
```rust
    for index in start_index..end_index {
        let name = *wad.lump_name(index);
        match Image::from_buffer(&try!(wad.read_lump(index))) {
            Ok(texture) => textures.insert(name, texture),
            Err(e) => {
                warn!("Skipping sprite: {}", BadImage(name, e));
                continue;
            }
        };    // rustfmt removes this semicolon
    }
```

By removing that semicolon, the `match` returns an `Option<...>`, and for loops don't want the last expression to return anything other than `()`. So rustfmt here actually _breaks_ code.

(workaround is, of course to put braces around the `textures.insert(...)` and add a semicolon there)

**Comment by marcusklaas** [comment] 2015-10-31 16:07
This is a dupe of https://github.com/nrc/rustfmt/issues/542.

**Closed by marcusklaas** 2015-10-31 16:07 UTC
